### ISSUE TITLE
Change the stack to a double ended queue?

### ISSUE THREAD

**Issue by crcx** [crcx/parable#11]
It's been suggested that the stack become a double ended queue (or deque for short).

This would have some interesting possibilities as code could access data from either end. But I'm not sure how useful this would actually be in practice, if the additional complexity in implementation would be worthwhile, or how specifying which end should be done.

I'm hoping to get some feedback on this.

[1] https://en.wikipedia.org/wiki/Double-ended_queue

**Comment by crcx** [comment]
Doing a little musing on this, having a deque would allow for both LIFO (the traditional model) and FIFO approaches to the stack.

FIFO is fundamentally different to LIFO, and I have a harder time mentally approaching it. Consider:

    1 4 3 5 + *

In a LIFO model, this would flow out as:

    1 4 3 5 + *
    1 4 8 *
    1 32

Wheras in FIFO, we'd have:

    1 4 3 5 + *
    3 5 5 *
    15 5

Adding support for this would require (at a minimum):

* reworking precheck() to support checking arguments from the beginning of the stack
* reworking stack_pop() to support popping values off of either end of the stack
* new syntax forms in the compiler for indicating whether to use FIFO or LIFO (add a suffix?)

**Comment by kiy** [comment]
i was hoing that deque would reduce the use of 'reverse' , 
which has been haunting me since i began to use parable.

however, now i think there is no need to "cook" slices
in the same data structure as the one used for parameter passing.
what i want to do seems essentially the same as text line editing,
except that i edit a slice of cells in place of a line of characters.
if i do it in a separate buffer, it will be more convenient than
doing the same on the stack.

so my conclusion at the moment is that the problem is 
with my prgramming skill, not worth bothering you.
i will continue using stacks trying to operate on slices in separate buffers. 
will let you know if i find that a deque is better than a stack in any way.

thank you again for having given it serious considerations.

**Comment by crcx** [comment]
Closing this for now. The underlying stack functions now support use as a deque (not enabled in the main Parable source currently), but **precheck()** would still need modification. I may revisit this at a later time.
