### ISSUE TITLE
syntax about function definition

### ISSUE THREAD

**Issue by xieyuheng** [crcx/parable#4]
is it possible to get back Forth-like syntax (actually cicada-like syntax)
in parable (maybe by syntax extension ?)

to change

```
[ &STATUS @ #2 / floor &STATUS ! ] 'even' define
```

into

```
: even
  &STATUS @ #2 /
  floor &STATUS !
; define-function
```

**Comment by xieyuheng** [comment]
to do another compare for fun ::

* first
```
     define-function factorial
       << n -- n! >>
       dup one? if
         end
       then
       dup sub1 factorial *
       end
     end
```

* second
```
     : factorial
       << n -- n! >>
       dup one? if
         end
       then
       dup sub1 factorial *
       end
     ; define-function
```

**Comment by crcx** [comment]
For this, I'd use a front end translator (something I'm exploring with Apologue, the iOS interface to Parable). I've written some translators that can take Forth-style syntax and convert it into Parable. See https://github.com/crcx/parable/blob/master/translators/rx2p.py

Parable's parser wants definitions to be on a single line. Apologue, which uses a server side component to execute code, uses a translator to get around this by allowing \ at the end of a line to join it with the next. The code for this is:

    def condenseLines(code):
        m = len(code)
        s = ''
        r = []
        i = 0
        c = 0
        while i < m:
            if code[i].endswith(' \\\n'):
                s = s + ' ' + code[i][:-2].strip()
                c = 1
            else:
                c = 0
                s = s + ' ' + code[i]
            if c == 0:
                if s != '' and s != ' \n':
                    r.append(s.strip())
                s = ''
            i = i + 1
        return r

Coupling this with the Forth/Retro translator would allow something close to what you are looking for, apart from recursion. (Since recursion is handled through redefinition in Parable, a little trickery would be needed to detect it, and then insert an empty definition initially. E.g., your example:

     : factorial
       << n -- n! >>
       dup one? if
         end
       then
       dup sub1 factorial *
       end
     ; define-function

Would need to compile into something like:

    [ ] 'factorial' define
    [ "n -- n!"  dup one? [ end ] if-true dup sub1 factorial * end ] 'factorial' define

I may try to write a translator for this soon. It could be beneficial. Do you separate functions with a blank line? (I need to figure out some way to identify where a function ends for the translation to be successful).

**Comment by xieyuheng** [comment]
there is a word ":" in front of "factorial"

and a ";" in front of "define-function"

I think your last question is due to a neglect of these little chars

(I also found they are hard to be recognized under the font github is using)

these two words identifies the beginning and the end of a function definition

------------------------------

in detail, my interpreter views the following as a string :
```
: factorial
  << n -- n! >>
  dup one? if
    end
  then
  dup sub1 factorial mul
  end
;
```

i.e. the same as :
```
"factorial
  dup one? if
    end
  then
  dup sub1 factorial mul
  end"
```

------------------------------

thank you for considering to write a translator ^-^

but IMO it is too early to do so

for my language is so un-mature

------------------------------

I think more documentations as design reviews

would be more appropriate and much easier to achieve

------------------------------

I would like to write some docs to compare syntax and implementation technology 

hopefully, soon :)
